### PR TITLE
Support for Astro 4

### LINKED ISSUE #122: Astro 4 support
This integration is not compatible with Astro 4 that was released today. When installing/updating the package the following error is shown:

```
npm install @sanity/astro
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While hidden@0.0.1
npm ERR! Found: astro@4.0.1
npm ERR! node_modules/astro
npm ERR!   astro@"^4.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer astro@"^2.0.0 || ^3.0.0" from @sanity/astro@2.1.4
npm ERR! node_modules/@sanity/astro
npm ERR!   @sanity/astro@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

It looks that this package is locked to Astro v2 and v3. I think Astro 4 also has some breaking changes for plugin authors. For example they are now using Vite 5.

Their upgrade guide:
https://docs.astro.build/en/guides/upgrade-to/v4/

### PR DESCRIPTION
**Pull request by olach**
I *think* this is all that is needed to add support for Astro 4. Fixes #122

### CODE REVIEW

**Comment by kmelve** [comment]
This seems to do the trick – thanks!

**Comment by olach** [comment]
Maybe we should remove the peer dependency for specific Astro versions in this package? When the next major Astro version is released, we shouldn't need to update this package if there are no breaking changes. What do you think?

**Review by kmelve — APPROVED** [review]

**Comment by kmelve** [comment]
@olach I'll just approve this for now to get it done™, but that might be the way to go in the future.

**Comment by Rithvik-Upadhya** [comment]
Hi @kmelve, do you know when this update will be reflected as a new version on npm? 
Happy holidays :)

**Pull request merged**
